apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kubernetes-discoverer
    cluster: k8s
  name: k8s-kubernetes-discoverer
  namespace: gimbal-discovery
spec:
  selector:
    matchLabels:
      app: kubernetes-discoverer
      cluster: k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-discoverer
        cluster: k8s
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - image: 10.121.50.40:5000/heptio-images/gimbal-discoverer:v0.2.0
        imagePullPolicy: Always
        name: kubernetes-discoverer
        command: ["/kubernetes-discoverer"]
        args: ["--discover-kubecfg-file", "/etc/remote-discover-kubecfg/config", "--backend-name", "$(CLUSTER_NAME)"]
        env:
        - name: CLUSTER_NAME
          value: "test-cluster"
      dnsPolicy: ClusterFirst
      serviceAccountName: gimbal-discoverer
      terminationGracePeriodSeconds: 30
