apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: contour
  name: contour
  namespace: gimbal-contour
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contour
  template:
    metadata:
      labels:
        app: contour
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: contour
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - serve
        - --kubeconfig
        - ""
        - --masterUrl
        - 10.18.33.173:8080
        - --xds-address
        - 0.0.0.0
        - --xds-port
        - $(CONTOUR_SERVICE_PORT)
        - --envoy-http-port
        - "80"
        command: ["contour"]
        image: 10.121.50.40:5000/heptio-images/contour:v0.6.0-alpha.2
        imagePullPolicy: Always
        name: contour
        ports:
        - containerPort: 8001
          name: xds
          protocol: TCP
      dnsPolicy: ClusterFirst
      serviceAccountName: contour
